// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: exam_user.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createExamUser = `-- name: CreateExamUser :one
insert into exam_user(id, created_at, updated_at, examid, userid, score, remaining_time, status)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, created_at, updated_at, userid, examid, score, remaining_time, status
`

type CreateExamUserParams struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Examid        uuid.UUID
	Userid        uuid.UUID
	Score         int32
	RemainingTime int32
	Status        ExamUserStatus
}

func (q *Queries) CreateExamUser(ctx context.Context, arg CreateExamUserParams) (ExamUser, error) {
	row := q.db.QueryRowContext(ctx, createExamUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Examid,
		arg.Userid,
		arg.Score,
		arg.RemainingTime,
		arg.Status,
	)
	var i ExamUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Userid,
		&i.Examid,
		&i.Score,
		&i.RemainingTime,
		&i.Status,
	)
	return i, err
}
