// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: question.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :one
insert into question(id, created_at, updated_at, question, option1, option2, option3, option4, correct, examid)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
returning id, created_at, updated_at, question, option1, option2, option3, option4, correct, examid
`

type CreateQuestionParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Question  string
	Option1   string
	Option2   string
	Option3   string
	Option4   string
	Correct   string
	Examid    uuid.UUID
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Question,
		arg.Option1,
		arg.Option2,
		arg.Option3,
		arg.Option4,
		arg.Correct,
		arg.Examid,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Question,
		&i.Option1,
		&i.Option2,
		&i.Option3,
		&i.Option4,
		&i.Correct,
		&i.Examid,
	)
	return i, err
}
