export {default as HomeLayOut} from './HomeLayOut'
export {default as ErrorPage} from './ErrorPage'
export {default as Landing} from './Landing'
export {default as About} from './About'
export {default as Login} from './Login'
export {default as Register} from './Register'