export {default as HomeLayOut} from './HomeLayOut'
export {default as ErrorPage} from './ErrorPage'
export {default as Landing} from './Landing'
export {default as About} from './About'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as MyTests} from './MyTests'
export {default as AdminLayout} from './AdminLayout'
export {default as SingleTest} from './SingleTest'
export {default as OnGoingTest} from './OnGoingTest'
export {default as ShowResult} from './ShowResult'
export {default as AdminLanding} from './AdminLanding'
export {default as AdminInsights} from './AdminInsights'
export {default as AddQuestion} from './AddQuestion'
export {default as EditTest} from './EditTest'
// export {default as StartTest} from './StartTest'